import React, { useRef } from "react";
import NewsCard from "./NewsCard";
import FrenchImg from "../../Assets/french proficiency.png";
import Averaged from "../../Assets/average scores accepted.png";
import Right from "../../Assets/application fee hiked.png";
import Working from "../../Assets/working hours increased.png";
import Changes from "../../Assets/processing time and backlog.jpg";
import Major from "../../Assets/Major provinces issue PNP invitations.jpg";
import { MdChevronLeft, MdChevronRight } from "react-icons/md";
const Component4 = () => {
  const sliderRef = useRef(null);

  const newsData = [
    {
      title: "Major Provinces Issue PNP Invitations",
      description:
        "Much to the delight of candidates who had applied for PNP in British Columbia, Manitoba and Quebec, these major provinces have issued Invitations to Apply to various Permanent Residency (PR) applicants. In the past few months this year, these provinces issued Invitations to Apply (ITAs) under the PNP draws.",
      image: Major,
      date: "7 JUN 2024",
      path: "/latest-news/major-provinces-issue-pnp-invitations",
    },
    {
      title: "Right of Permanent Resident fee increased",
      description:
        "Canada's right of permanent residence fee (RPRF) has been significantly increased, with a substantial hike of 12%.",
      image: Right,
      date: "30 APR 2024",
      path: "/latest-news/right-of-permanent-resident-fee-increased",
    },
    {
      title:
        "Averaged Language Scores now Accepted under Express Entry for Disabled Candidates",
      description:
        "Averaged language scores generated by the respective language organisation will now be accepted under Express Entry only for candidates living with physical or mental disability.",
      image: Averaged,
      date: "29 APR 2024",
      path: "/latest-news/averaged-language-scores-now-accepted-under-express-entry-for-disabled-candidates",
    },

    {
      title: "Working hours Increased for Students in Canada",
      description:
        "As of April 29th 2024, working hours for students will be increased; for both during academic session and.",
      image: Working,
      date: "29 APR 2024",
      path: "/latest-news/working-hours-increased-for-students-in-canada",
    },
    {
      title: "Changes in Federal Business Programs to tackle Backlog issue",
      description:
        "Changes have been announced to the Start-up visa and Self-Employed Persons programs to manage backlogs and improve processing time.",
      image: Changes,
      date: "29 APR 2024",
      path: "/latest-news/changes-in-federal-business-programs-to-tackle-backlog-issue",
    },
    {
      title: "French Proficiency Leads Category-Based Selections",
      description:
        "French language proficiency will now be at the forefront of category-based selections in express entry draws in 2024.",
      image: FrenchImg,
      date: "26 APR 2024",
      path: "/latest-news/french-proficiency-leads-category-based-selection",
    },
  ];

  const slideLeft = () => {
    if (sliderRef.current) {
      sliderRef.current.scrollLeft -= sliderRef.current.offsetWidth;
    }
  };

  const slideRight = () => {
    if (sliderRef.current) {
      sliderRef.current.scrollLeft += sliderRef.current.offsetWidth;
    }
  };

  return (
    <div className="h-auto mt-[2rem] lg:mt-[7rem] px-4 pt-4 lg:pt-20 lg:px-20 pb-10 bg-gradient-to-r from-white to-slate-50 mb-[6rem]">
      <div className="w-full lg:w-[70%]">
        <div className="text-[1.8rem] md:text-[3rem] font-semibold flex items-center gap-[6px] justify-center md:block mt-14 mb-8">
          Latest <span className="text-[#019989]"> News</span>
        </div>
        {/* <div className='text-[3rem] font-semibold mx-[0.2rem] lg:mx-[3.8rem] my-4'>
          Latest <span className='text-[#019989]'>News</span>
        </div> */}
      </div>
      <div className="flex flex-col ">
        <div
          ref={sliderRef}
          id="slider"
          className="overflow-hidden overflow-x-scroll scroll scroll-smooth flex items-center justify-around w-full gap-10 scrollbar-hide pr-20"
        >
          {newsData.map((item, index) => (
            <NewsCard key={index} data={item} />
          ))}
        </div>
        <div className="hidden lg:flex items-center justify-end w-full -ml-10 mt-4">
          <MdChevronLeft
            size={30}
            onClick={slideLeft}
            className="cursor-pointer hover:scale-110 mr-8 mt-1 text-black shadow-lg flex items-center bg-white justify-between rounded-[10px] transition ease-in delay-40 duration-200"
          />
          <MdChevronRight
            size={30}
            onClick={slideRight}
            className="cursor-pointer hover:scale-110 mr-8 mt-1 text-black shadow-lg bg-[#00F8E1] flex items-center justify-between rounded-[10px] transition ease-in delay-40 duration-200"
          />
        </div>
      </div>
    </div>
  );
};

export default Component4;
